# General
name: Chase Florell
description: ".NET Blogger"
url: https://chaseflorell.github.io

markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

paginate: 5
permalink: /:categories/:year/:month/:day/:title/

#github
github_repo_url: https://github.com/ChaseFlorell/chaseflorell.github.io/

# Social share and comments.
disqus-id: ChaseFlorell
twitter: ChaseFlorell
##github: ChaseFlorell
google: +ChaseFlorell
facebook: ChaseFlorell

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"

# Analytics
google-analytics:
  tracking_id: UA-62354301-1